services:
  - type: web
    name: contractsama
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: CONTRACT_PREFIX
        value: B123-1447
      - key: DATABASE_URL
        fromDatabase:
          name: contractsama-postgres
          property: connectionString
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USE_TLS
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      # إضافات لضبط البيئة والتوافق
      - key: PYTHON_VERSION
        value: 3.11
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WEB_CONCURRENCY
        value: "2"
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 180 --graceful-timeout 30"
      - key: RENDER
        value: "1"
    disk:
      name: signatures
      mountPath: /opt/render/project/src/static/uploads/signatures
      sizeGB: 1

databases:
  - name: contractsama-postgres
    plan: free
